# Generated by Django 5.2.6 on 2025-09-29 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callrail_id', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('gclid', models.CharField(blank=True, max_length=512, null=True)),
                ('lead_status', models.CharField(max_length=64)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopmonkeyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('total_cents', models.BigIntegerField()),
                ('archived', models.BooleanField(default=False)),
                ('raw', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gclid', models.CharField(max_length=512)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.shopmonkeyorder')),
            ],
        ),
    ]
