# Generated by Django 5.2.6 on 2025-10-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='caller_city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='caller_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='caller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='caller_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='destination_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='timeline_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='lead_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
