# Generated by Django 5.2.6 on 2025-10-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_callrecord_caller_city_callrecord_caller_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecord',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='destination_number',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='score',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='timeline_url',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='utm_source',
        ),
    ]
